# Revenue
#total revenue (food delivery app)
select sum((total_expense-commission)) as Revenue 
from monthly_member_totals;
#revenue by month (food delivery app)
select month,sum((total_expense-commission)) as Revenue 
from monthly_member_totals
group by month
order by revenue desc;

#restaurants with high revenue(income percentage)
with restaurant_order_price as
(
select restaurant_name, sum(total_order) as total_order_price,max(income_percentage) as inc_pct
from
orders o 
join restaurants r
on o.restaurants_id=r.id
group by restaurant_name
order by total_order_price desc)

select restaurant_name,total_order_price,round((total_order_price*inc_pct),2) as Revenue from restaurant_order_price 
order by Revenue desc limit 10;

#identify most profitable customer for platform(revenue generated by a particular customer)
select concat(first_name," ",surname) as name,sum((total_expense-commission)) as Revenue 
from monthly_member_totals
group by name
having Revenue>4500
order by revenue desc;

# understanding customer exceeds their budgets(budget vs actual spending)
with customer_budget as (
select concat(first_name," ",surname) as name ,monthly_budget as target , total_expense as actual_spending 
from monthly_member_totals mmt)
select  name , target , actual_spending ,
(target-actual_spending) as target_actual
from customer_budget
order by target_actual ;

#restaurants with high revenue(income percentage)
with restaurant_order_price as
(
select restaurant_name, sum(total_order) as total_order_price,max(income_percentage) as inc_pct
from
orders o 
join restaurants r
on o.restaurants_id=r.id
group by restaurant_name
order by total_order_price desc)

select restaurant_name,total_order_price,round((total_order_price*inc_pct),2) as Revenue from restaurant_order_price 
order by Revenue desc limit 10;

#order_count by restaurants
select restaurant_name,count(o.id) as total_orders
from orders o
join restaurants r
on o.restaurants_id=r.id
group by restaurant_name
order by total_orders desc;

#order_count by city
select city,count(o.id) as total_orders
from orders o
join restaurants r
on o.restaurants_id=r.id
join cities c 
on r.cities_id=c.id
group by city
order by total_orders desc;

#avg meals_count per order
with mealcount_per_order as
(select order_id,(count(meals_id)) as total_meals
from order_details
group by order_id)

select avg(total_meals) as avg_meals_per_order
from  mealcount_per_order;

#order avg price by restaurants
with avg_order_price as
(
select 
       restaurant_name,total_order,city
from orders o 
join restaurants r
on o.restaurants_id=r.id
join cities c
on c.id=r.cities_id
)
select restaurant_name, avg(total_order) as avg_price ,city
from avg_order_price
group by restaurant_name,city
order by avg_price desc;

# average order per meal_type
select round(avg(total_order),2) as avg_price from orders;

with avg_meal_price as
(
select 
       meal_type,total_order
from orders o 
join order_details od
on o.id=od.order_id
join meals me
on me.id=od.meals_id
join meal_types mt
on me.meal_types_id=mt.id
)
select meal_type, avg(total_order) as avg_price
from avg_meal_price
group by meal_type
order by avg_price desc;

#peak ordering hours
select  hour(hour) as hours,
		count(id) as no_of_orders
 from orders 
group by hours
order by no_of_orders desc ;

# Q3 monthwise top 5 customers
WITH Monthwise_top_customer AS (
    SELECT  
        CONCAT(m.first_name, ' ', m.surname) AS customer_name, 
        mmt.order_count,
        mmt.month
    FROM members m
    JOIN monthly_member_totals mmt
        ON m.id = mmt.members_id
)

SELECT *
FROM (
    SELECT 
        customer_name,
        month,
        order_count,
         DENSE_RANK() OVER (
            PARTITION BY month 
            ORDER BY order_count DESC
        ) AS rnk
    FROM Monthwise_top_customer
) t
WHERE rnk <= 5;

#  meal type by gender
with mealstype_gender as
(select sex,count(o.id) as total_orders ,meal_type
from members m
join orders o 
on m.id=o.members_id
join order_details od
on o.id=od.order_id
join meals me
on me.id=od.meals_id
join meal_types mt
on mt.id=me.meal_types_id
group by sex,meal_type
)
select * 
from( select  
             sex,
			 meal_type,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from mealstype_gender) t
where rnk<=5 ;


#Q3 top customers as per order_count
select  concat(m.first_name," ",m.surname) as customer_name, sum(order_count) as Total_times_order,m.sex
from members m
inner join monthly_member_totals mmt
on m.id=mmt.members_id
group by m.id
having Total_times_order>=150
order by Total_times_order desc;

# top rest category by gender 
with Rest_Members as
(select sex,count(o.id) as total_orders ,restaurant_types
from members m
join orders o 
on m.id=o.members_id
join restaurants r
on o.restaurants_id=r.id
join restaurant_types rt
on r.restaurant_types_id=rt.id
group by sex,restaurant_types
)
select * 
from( select  
             sex,
			 restaurant_types,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from Rest_Members) t
where rnk<=5 ;

# top rest category by gender 
with Rest_Members as
(select sex,count(o.id) as total_orders ,restaurant_types
from members m
join orders o 
on m.id=o.members_id
join restaurants r
on o.restaurants_id=r.id
join restaurant_types rt
on r.restaurant_types_id=rt.id
group by sex,restaurant_types
)
select * 
from( select  
             sex,
			 restaurant_types,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from Rest_Members) t
where rnk<=5 ;

#top meals or restaurant by gender(windows, partition by gender top 5)
#steps->join members,orders,restaurants table

with Rest_Members as
(select sex,count(o.id) as total_orders ,restaurant_name,city
from members m
join orders o 
on m.id=o.members_id
join restaurants r
on o.restaurants_id=r.id
join cities c
on c.id=r.cities_id
group by sex,restaurant_name,city
)
select * 
from( select  
             sex,
			 restaurant_name,
             city,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from Rest_Members) t
where rnk<=10 ;

#Q2 
With City_Orders AS 
(select c.city as City ,o.id as order_id
from cities c
inner join restaurants r
on c.id=r.cities_id
inner join orders o
on r.id=o.restaurants_id)

select City,count(order_id) as num_of_orders
from City_Orders 
group by City 
order by num_of_orders desc;

#popular restaurants by restaurants type
# top restaurants in each category
WITH Top_rest_categorywise AS (
    SELECT  
        restaurant_types , 
       restaurant_name,
	   count(o.id) as order_count
    FROM restaurant_types rt
    JOIN restaurants r
        ON rt.id = r.restaurant_types_id
	join orders o
    on r.id=o.restaurants_id
    group by restaurant_name,restaurant_types
)
SELECT *
FROM (
    SELECT 
        restaurant_types,
       restaurant_name,
        order_count,
         DENSE_RANK() OVER (
            PARTITION BY restaurant_types
            ORDER BY order_count DESC
        ) AS rnk
    FROM Top_rest_categorywise
) t
WHERE rnk <= 3;


# popular meals
select  meal_name,count(order_id) as Order_frequency from order_details
join meals
on meals.id=order_details.meals_id
group by meals_id 
order by Order_frequency desc limit 5;

#popular meal_types
select  meal_type,count(od.id) as Order_frequency
 from meal_types mt
join meals m
on mt.id=m.meal_types_id
join order_details od
on m.id=od.meals_id
group by meal_type
order by Order_frequency desc ;


# popular restaurant categories(rest_type)
select  restaurant_types,count(o.id) as Order_frequency
 from restaurant_types rt
join restaurants r
on rt.id=r.restaurant_types_id
join orders o
on r.id=o.restaurants_id
group by restaurant_types
order by Order_frequency desc ;

#popular restaurants
select  restaurant_name,count(o.id) as Order_frequency
 from restaurants r
join orders o
on r.id=o.restaurants_id
group by restaurant_name
order by Order_frequency desc limit 10;


#same pattern for meal types , restaurant type and order count for gender , but different patterns for actual restaurants and city
#orders by gender
select sex, count(o.id) as total_orders
from members m
join orders o
on m.id=o.members_id
group by sex
order by total_orders desc;









